//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_conect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> lowRange { get; set; }
        public int highRange { get; set; }
        public int avgServiceTime { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
