//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int service { get; set; }
        public string image1 { get; set; }
    
        public virtual Service Service1 { get; set; }
    }
}
