//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int id { get; set; }
        public bool showDetails { get; set; }
        public string priceFor { get; set; }
        public int price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string title { get; set; }
    }
}
