//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string lastName { get; set; }
        public string description { get; set; }
        public string phonNumber { get; set; }
        public string Email { get; set; }
        public int likes { get; set; }
        public string firstName { get; set; }
    }
}
